### ISSUE TITLE
Investigate the upgrade process for VR Teleop

### ISSUE THREAD

**Issue by PeterMitrano** [UM-ARM-Lab/vr_teleop#11]

**Comment by PeterMitrano** [comment]
Things to investigate

 - [ ] Update Unity to the latest version that is compatible with the Vive
 - [ ] Create new Unity VR Project and test that we can read data from the Vive
 - [ ] Create a C sharp ROS2 project
 - [ ] Put those two projects together so we can publish to ROS from a Unity VR Project
 - [ ] Re-implement a controller that sends delta gripper pose and gripper commands via ROS when the trigger is pulled

Stretch goals

 - [ ] Add a subscriber to a wrench topic that buzzes

**Comment by mvandermerwe** [comment]
- Unity has [official ROS support](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/ros_unity_integration/README.md).
- HTC Vive now recommends using [OpenXR](https://developer.vive.com/resources/openxr/) for development. This also makes the code more cross-platform for VR devices in case we upgrade/switch headsets in the future.

**Comment by PeterMitrano** [comment]
Possible future TODOs
 - [ ] Add a subscriber to a wrench topic that buzzes

**Comment by PeterMitrano** [comment]
The new repo & instructions are here: https://github.com/UM-ARM-Lab/vr_ros2_bridge
